// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import './globals.css'
import "@radix-ui/themes/styles.css"
import { Theme, Flex, Text, Button, ThemePanel } from '@radix-ui/themes'
import { dark } from '@clerk/themes'


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark
    }}>
      <html lang="en">
        <body>
          <Theme appearance='dark' accentColor="violet" grayColor="sage" radius="small">
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <div className='text-white bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 ... p-1 text-right'>
                <UserButton showName/>
              </div>
            </SignedIn>
            {/* <ThemePanel /> */}
            {children}
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  )
}